turn_zone_on:
  description: Turn on a zone.
  fields:
    entity_id:
      description: Name of the climate entity
      example: climate.bonaire_myclimate
    zone:
      description: Which zone to turn on
      example: 2
turn_zone_off:
  description: Turn off a zone.
  fields:
    entity_id:
      description: Name of the climate entity
      example: climate.bonaire_myclimate
    zone:
      description: Which zone to turn off
      example: 2